[package]
name = "st2ical"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.37.2"

[dependencies.gtk4]
package = "gtk4"
version = "0.9.6"
features = ["v4_10"]

[build-dependencies]
glib-build-tools = "0.20.0"
